# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        self.menuCalculoAreas = QtWidgets.QMenu(parent=self.menubar)
        self.menuCalculoAreas.setObjectName("menuCalculoAreas")
        self.menuSalir = QtWidgets.QMenu(parent=self.menubar)
        self.menuSalir.setObjectName("menuSalir")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionCirculo = QtGui.QAction(parent=MainWindow)
        self.actionCirculo.setObjectName("actionCirculo")
        self.actionTriangulo = QtGui.QAction(parent=MainWindow)
        self.actionTriangulo.setObjectName("actionTriangulo")
        self.actionRectangulo = QtGui.QAction(parent=MainWindow)
        self.actionRectangulo.setObjectName("actionRectangulo")
        self.actionCuadrado = QtGui.QAction(parent=MainWindow)
        self.actionCuadrado.setObjectName("actionCuadrado")
        self.actionSalir = QtGui.QAction(parent=MainWindow)
        self.actionSalir.setObjectName("actionSalir")
        self.menuCalculoAreas.addAction(self.actionCirculo)
        self.menuCalculoAreas.addAction(self.actionTriangulo)
        self.menuCalculoAreas.addAction(self.actionRectangulo)
        self.menuCalculoAreas.addAction(self.actionCuadrado)
        self.menuSalir.addAction(self.actionSalir)
        self.menubar.addAction(self.menuCalculoAreas.menuAction())
        self.menubar.addAction(self.menuSalir.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Calculadora de Áreas"))
        self.menuCalculoAreas.setTitle(_translate("MainWindow", "&Cálculo de Áreas"))
        self.menuSalir.setTitle(_translate("MainWindow", "&Salir"))
        self.actionCirculo.setText(_translate("MainWindow", "Círculo"))
        self.actionCirculo.setShortcut(_translate("MainWindow", "Ctrl+A"))
        self.actionTriangulo.setText(_translate("MainWindow", "Triángulo"))
        self.actionRectangulo.setText(_translate("MainWindow", "Rectángulo"))
        self.actionCuadrado.setText(_translate("MainWindow", "Cuadrado"))
        self.actionSalir.setText(_translate("MainWindow", "Salir"))
        self.actionSalir.setShortcut(_translate("MainWindow", "Ctrl+Q"))
